steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'pull', 'gcr.io/$PROJECT_ID/api.dungeon.studio' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '--cache-from', 'gcr.io/$PROJECT_ID/api.dungeon.studio',
            '-t', '$_IMAGE_NAME',
            '-f', 'Dockerfile', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'login', '--username=_', '--password=$_HEROKU_API_KEY', 'registry.heroku.com' ]

images:
  - '$_IMAGE_NAME'

timeout: 60m
