steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/dungeon-studio', '.' ]
images:
  - 'gcr.io/$PROJECT_ID/dungeon-studio'
tags:
  - "$TAG_NAME"
  - "$BRANCH_NAME"
  - "$COMMIT_SHA"
