steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'pull', 'gcr.io/$PROJECT_ID/builder-api.dungeon.studio' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'pull', 'gcr.io/$PROJECT_ID/api.dungeon.studio' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '--cache-from', 'gcr.io/$PROJECT_ID/builder-api.dungeon.studio',
            '-t', 'gcr.io/$PROJECT_ID/builder-api.dungeon.studio',
            '--target', 'builder',
            '-f', 'Dockerfile', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '--cache-from', 'gcr.io/$PROJECT_ID/builder-api.dungeon.studio',
            '--cache-from', 'gcr.io/$PROJECT_ID/api.dungeon.studio',
            '-t', 'gcr.io/$PROJECT_ID/api.dungeon.studio',
            '-t', 'gcr.io/$PROJECT_ID/api.dungeon.studio:$BRANCH_NAME',
            '-t', 'gcr.io/$PROJECT_ID/api.dungeon.studio:$COMMIT_SHA',
            '-f', 'Dockerfile', '.' ]

images:
  - 'gcr.io/$PROJECT_ID/builder-api.dungeon.studio'
  - 'gcr.io/$PROJECT_ID/api.dungeon.studio'
  - 'gcr.io/$PROJECT_ID/api.dungeon.studio:$BRANCH_NAME'
  - 'gcr.io/$PROJECT_ID/api.dungeon.studio:$COMMIT_SHA'

timeout: 60m
