version: "3"

services:
  collection-server:
    build:
      context: .
      dockerfile: Dockerfile.collection-server
    environment:
      - COLLECTION_SERVER_PORT=33080
      - COLLECTION_SERVER_RESOURCE_PATH=/srv
    image: dungeon-studio/collection-server:latest
    networks:
      - dungeon-studio
    ports:
      - "33080:33080"
    volumes:
      - ./resources/earthdawn:/srv/earthdawn

  dungeon-studio:
    build:
      context: .
      dockerfile: Dockerfile.dungeon-studio
    environment:
      - BOLT_HOST=neo4j
      - BOLT_PORT=7687
      - DUNGEON_STUDIO_PORT=45753
    image: dungeon-studion/dungeon-studio:latest
    links:
      - neo4j:neo4j
    networks:
      - dungeon-studio
    ports:
      - "45753:45753"

  neo4j:
    environment:
      - NEO4J_AUTH=none
    image: neo4j:3.2
    logging:
      driver: none
    networks:
      - dungeon-studio
    ports:
      - "7474:7474"
      - "7687:7687"

networks:
  dungeon-studio:
